[config]
version_check = false

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.hyprland_lua]
input_path = "~/.config/matugen/templates/palette.lua"
output_path = "~/.config/hypr/palette.lua"

[templates.kitty]
input_path = "~/.config/matugen/templates/colors-kitty.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.quickshell]
input_path = "~/.config/matugen/templates/colors.json"
output_path = "~/.cache/quickshell_colors.json"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-3.0/gtk.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-4.0/gtk.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.kde_colors]
input_path = "~/.config/matugen/templates/kde/color.txt"
output_path = "~/.local/state/quickshell/user/generated/color.txt"
