[General]
# SDDM & Lockscreen General Config
background=background.png
blurRadius=42
clockBlurRadius=46
glassSheen=48
clockFont=OpenSans.ttf
clockFontSize=124
showDate=true
showSession=true
showPower=true
showAvatar=true
timeFormat24h=false
basicTextColor=#ffffff
passwordMask=true
