[General]
# SDDM & Lockscreen General Config
background=background.png
blurRadius=80
clockBlurRadius=64
glassSheen=90
clockFont=OpenSans.ttf
clockFontSize=120
showDate=true
showSession=true
showPower=true
showAvatar=true
timeFormat24h=false
basicTextColor=#ffffff
passwordMask=true
