# ▄▀█ █▀█ █▀█ █▀
# █▀█ █▀▀ █▀▀ ▄█

$terminal = kitty
$fileManager = nautilus
$menu = quickshell -p ~/.config/quickshell/AppLauncher.qml
$browser = google-chrome-stable
$taskManager = btop
$colorpicker = hyprpicker

# █▀▀ █░█ █▀█ █▀ █▀█ █▀█
# █▄▄ █▄█ █▀▄ ▄█ █▄█ █▀▄

env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = WLR_NO_HARDWARE_CURSORS,1
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = GBM_BACKEND,nvidia-drm

cursor {
    no_hardware_cursors = true
}
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/transparency.conf
source = ~/.config/hypr/animation.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinding.conf
source = ~/.config/hypr/layouts.conf
decoration {
    shadow {
        enabled = false
    }
}
