
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

##===> Opacity & Blur
############################################
windowrule = no_blur 1, match:class ^()$, match:title ^()$
windowrule = opacity 0.90 0.90, match:class ^(.*)$, match:title ^(.*)$
windowrule = opacity 1 1, match:class ^(firefox)$

##===> Picture In Picture
############################################
windowrule = float 1, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = keep_aspect_ratio 1, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = move 74.5% 74%, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = size 25% 25%, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = pin 1, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$

##===> idleinhibit rules
############################################
windowrule = idle_inhibit fullscreen, match:class ^(.*celluloid.*)$|^(.*mpv.*)$|^(.*vlc.*)$
windowrule = idle_inhibit fullscreen, match:class ^(.*[Ss]potify.*)$
windowrule = idle_inhibit fullscreen, match:class ^(yandex-music)$
windowrule = idle_inhibit fullscreen, match:class ^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*brave-browser.*)$|^(.*firefox.*)$|^(.*chromium.*)$|^(.*zen.*)$|^(.*vivaldi.*)$

##===> Floating windows
############################################
windowrule = float 1, match:class ^(vlc)$
windowrule = float 1, match:class ^(blueman-manager)$
windowrule = float 1, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$
windowrule = float 1, match:class ^(firefox)$, match:title ^(Library)$
windowrule = float 1, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = float 1, match:class ^(qt5ct)$
windowrule = float 1, match:class ^(qt6ct)$
windowrule = float 1, match:class ^(org.kde.ark)$
windowrule = float 1, size 48% 42%, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float 1, match:class ^(yad)$
windowrule = float 1, center 1, size 19% 47%, match:class ^(gnome-calculator)$
windowrule = float 1, center 1, size 63% 74%, match:class ^(org.gnome.Loupe)$
windowrule = float 1, center 1, size 63% 74%, match:class ^(org.gnome.FileRoller)$
windowrule = float 1, center 1, size 63% 74%, match:class ^(com.cupcake.Keybinds)$
windowrule = float 1, center 1, size 45% 55%, match:class ^(qalculate-gtk)$

# modals
windowrule = float 1, match:title ^(Open)$
windowrule = float 1, match:title ^(Authentication Required)$
windowrule = float 1, match:title ^(Add Folder to Workspace)$
windowrule = float 1, match:initial_title ^(Open File)$
windowrule = float 1, match:title ^(Choose Files)$
windowrule = float 1, match:title ^(Save As)$
windowrule = float 1, match:title ^(Confirm to replace files)$
windowrule = float 1, match:title ^(File Operation Progress)$
windowrule = float 1, match:title ^(File Upload)(.*)$
windowrule = float 1, match:title ^(Choose wallpaper)(.*)$
windowrule = float 1, match:title ^(Library)(.*)$
windowrule = float 1, match:class ^(.*dialog.*)$
windowrule = float 1, match:title ^(.*dialog.*)$

# hyprland portal
windowrule = float 1, center 1, match:class ^(org.freedesktop.impl.portal.desktop.hyprland)$

# gtk portal
windowrule = float 1, center 1, match:class ^(org.freedesktop.impl.portal.desktop.gtk)$

# xdg-desktop-portal-gtk
windowrule = float 1, center 1, match:class ^([Xx]dg-desktop-portal-gtk)$

##===> Layer rules
############################################
layerrule = blur 1, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace notifications

# Cupcake Settings App
windowrulev2 = float, title:^(Cupcake Settings)$
